[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='0xc1856d74e5e6e4f523507998f121eb06cceea72d701dd019ea1e65755fc81ed9'

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"
